# -*- mode: ruby -*-
# vi: set ft=ruby :

@ansible_home = '/home/vagrant/.ansible'
@machines = [
  {
    :hostname => "ubuntu22",
    :box => "bento/ubuntu-22.04"
  },
  {
    :hostname => "ubuntu24",
    :box => "bento/ubuntu-24.04"
  }
]

Vagrant.configure("2") do |config|
  @machines.each do |machine|
    config.vm.define machine[:hostname] do |node|
      node.vm.box = machine[:box]

      node.vm.provider "virtualbox" do |vb|
        vb.linked_clone = true
        vb.memory = 2048
        vb.cpus = 2
      end

      node.vm.synced_folder "../", "#{@ansible_home}/roles/ansible-sury-php-fpm"
      node.vm.provision "shell", inline: "chown -R vagrant:vagrant #{@ansible_home}"

      node.vm.provision "setup", type: "ansible_local" do |ansible|
        ansible.playbook = "setup-basic.yml"
      end

      node.vm.provision "setup_roles", type: "ansible_local" do |ansible|
        ansible.playbook = "setup-roles.yml"
      end

      node.vm.provision "run_test", type: "ansible_local" do |ansible|
        ansible.playbook = "test.yml"
      end
    end
  end
end
