# -*- mode: ruby -*-
# vi: set ft=ruby :

@ansible_home = '/home/vagrant/.ansible'

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"

  config.vm.provider "virtualbox" do |vb|
    vb.linked_clone = true
    vb.memory = 1024
    vb.cpus = 1
  end

  config.vm.synced_folder "../", "#{@ansible_home}/roles/ansible-sury-php-fpm"
  config.vm.provision "shell", inline: "chown -R vagrant:vagrant #{@ansible_home}"

  config.vm.provision "setup", type: "ansible_local" do |ansible|
    ansible.playbook = "setup-basic.yml"
  end

  config.vm.provision "setup_roles", type: "ansible_local" do |ansible|
    ansible.playbook = "setup-roles.yml"
  end

  config.vm.provision "run_test", type: "ansible_local" do |ansible|
    ansible.playbook = "test.yml"
  end
end
